#!/usr/bin/env python3

import argparse
import evince_synctex

parser = argparse.ArgumentParser()
parser.add_argument('source_file')

cmdline = ['gnome-terminal', '--window', '--', 'vim', '%f', '+%l', '+norm zz']

if __name__ == '__main__':
    evince_synctex.main(cmdline=cmdline, **vars(parser.parse_args()))
